# Generated by Django 3.0.3 on 2020-04-28 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('estilo', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('instrumento', models.CharField(max_length=64)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciertos.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=64)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciertos.Grupo')),
            ],
        ),
    ]
